version: '3.8'

services:
  frontend:
    build:
      context: ./project-1747428226211
      dockerfile: Dockerfile
    ports:
      - "1234:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backend/chroma:/app/chroma
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge